default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: diabet-diary_development

test:
  <<: *default
  database: diabet-diary_test

production:
  <<: *default
  database: diabet-diary_production
  username: testerio
  password: <%= ENV['TESTERIO_DATABASE_PASSWORD'] %>